[package]
name = "icc-profile"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bin-rs = {version = "0.0.7",features = ["util"]}