[package]
name = "icc-profile-reader"
version = "0.0.1"
edition = "2021"
authors = ["Mith@mmk"]
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.icc-profile]
path = "../"